export const Movies = [
  { id: 1, title: "The Shawshank Redemption", year: 1994, genre: "Drama", rating: 9.3 },
  { id: 2, title: "The Godfather", year: 1972, genre: "Crime", rating: 9.2 },
  { id: 3, title: "The Dark Knight", year: 2008, genre: "Action", rating: 9.0 },
  { id: 4, title: "The Godfather Part II", year: 1974, genre: "Crime", rating: 9.0 },
  { id: 5, title: "12 Angry Men", year: 1957, genre: "Drama", rating: 9.0 },
  { id: 6, title: "Schindler's List", year: 1993, genre: "Biography", rating: 9.0 },
  { id: 7, title: "The Lord of the Rings: The Return of the King", year: 2003, genre: "Fantasy", rating: 9.0 },
  { id: 8, title: "Pulp Fiction", year: 1994, genre: "Crime", rating: 8.9 },
  { id: 9, title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, genre: "Fantasy", rating: 8.9 },
  { id: 10, title: "The Good, the Bad and the Ugly", year: 1966, genre: "Western", rating: 8.8 },
  { id: 11, title: "Forrest Gump", year: 1994, genre: "Drama", rating: 8.8 },
  { id: 12, title: "Fight Club", year: 1999, genre: "Drama", rating: 8.8 },
  { id: 13, title: "The Lord of the Rings: The Two Towers", year: 2002, genre: "Fantasy", rating: 8.8 },
  { id: 14, title: "Inception", year: 2010, genre: "Sci-Fi", rating: 8.8 },
  { id: 15, title: "Star Wars: Episode V - The Empire Strikes Back", year: 1980, genre: "Sci-Fi", rating: 8.7 },
  { id: 16, title: "The Matrix", year: 1999, genre: "Sci-Fi", rating: 8.7 },
  { id: 17, title: "Goodfellas", year: 1990, genre: "Biography", rating: 8.7 },
  { id: 18, title: "One Flew Over the Cuckoo's Nest", year: 1975, genre: "Drama", rating: 8.7 },
  { id: 19, title: "Se7en", year: 1995, genre: "Mystery", rating: 8.6 },
  { id: 20, title: "Interstellar", year: 2014, genre: "Sci-Fi", rating: 8.7 },
  { id: 21, title: "It's a Wonderful Life", year: 1946, genre: "Drama", rating: 8.6 },
  { id: 22, title: "Seven Samurai", year: 1954, genre: "Action", rating: 8.6 },
  { id: 23, title: "The Silence of the Lambs", year: 1991, genre: "Thriller", rating: 8.6 },
  { id: 24, title: "Saving Private Ryan", year: 1998, genre: "War", rating: 8.6 },
  { id: 25, title: "City of God", year: 2002, genre: "Crime", rating: 8.6 },
  { id: 26, title: "Life Is Beautiful", year: 1997, genre: "Comedy", rating: 8.6 },
  { id: 27, title: "The Green Mile", year: 1999, genre: "Drama", rating: 8.6 },
  { id: 28, title: "Star Wars: Episode IV - A New Hope", year: 1977, genre: "Sci-Fi", rating: 8.6 },
  { id: 29, title: "Terminator 2: Judgment Day", year: 1991, genre: "Action", rating: 8.6 },
  { id: 30, title: "Back to the Future", year: 1985, genre: "Adventure", rating: 8.5 },
  { id: 31, title: "Spirited Away", year: 2001, genre: "Animation", rating: 8.6 },
  { id: 32, title: "The Pianist", year: 2002, genre: "Biography", rating: 8.5 },
  { id: 33, title: "Parasite", year: 2019, genre: "Thriller", rating: 8.5 },
  { id: 34, title: "Psycho", year: 1960, genre: "Horror", rating: 8.5 },
  { id: 35, title: "Gladiator", year: 2000, genre: "Action", rating: 8.5 },
  { id: 36, title: "The Lion King", year: 1994, genre: "Animation", rating: 8.5 },
  { id: 37, title: "Léon: The Professional", year: 1994, genre: "Action", rating: 8.5 },
  { id: 38, title: "The Departed", year: 2006, genre: "Crime", rating: 8.5 },
  { id: 39, title: "American History X", year: 1998, genre: "Drama", rating: 8.5 },
  { id: 40, title: "Whiplash", year: 2014, genre: "Drama", rating: 8.5 },
  { id: 41, title: "The Prestige", year: 2006, genre: "Mystery", rating: 8.5 },
  { id: 42, title: "Grave of the Fireflies", year: 1988, genre: "Animation", rating: 8.5 },
  { id: 43, title: "Casablanca", year: 1942, genre: "Romance", rating: 8.5 },
  { id: 44, title: "Rear Window", year: 1954, genre: "Mystery", rating: 8.5 },
  { id: 45, title: "Alien", year: 1979, genre: "Horror", rating: 8.5 },
  { id: 46, title: "Apocalypse Now", year: 1979, genre: "War", rating: 8.4 },
  { id: 47, title: "Memento", year: 2000, genre: "Mystery", rating: 8.4 },
  { id: 48, title: "Raiders of the Lost Ark", year: 1981, genre: "Adventure", rating: 8.4 },
  { id: 49, title: "Django Unchained", year: 2012, genre: "Western", rating: 8.5 },
  { id: 50, title: "WALL·E", year: 2008, genre: "Animation", rating: 8.4 },
  { id: 51, title: "The Shining", year: 1980, genre: "Horror", rating: 8.4 },
  { id: 52, title: "Avengers: Infinity War", year: 2018, genre: "Action", rating: 8.4 },
  { id: 53, title: "Spider-Man: Into the Spider-Verse", year: 2018, genre: "Animation", rating: 8.4 },
  { id: 54, title: "Sunset Boulevard", year: 1950, genre: "Drama", rating: 8.4 },
  { id: 55, title: "Paths of Glory", year: 1957, genre: "War", rating: 8.4 },
  { id: 56, title: "Oldboy", year: 2003, genre: "Action", rating: 8.4 },
  { id: 57, title: "Princess Mononoke", year: 1997, genre: "Animation", rating: 8.4 },
  { id: 58, title: "Once Upon a Time in America", year: 1984, genre: "Crime", rating: 8.3 },
  { id: 59, title: "Braveheart", year: 1995, genre: "Biography", rating: 8.3 },
  { id: 60, title: "Your Name.", year: 2016, genre: "Animation", rating: 8.4 },
  { id: 61, title: "Coco", year: 2017, genre: "Animation", rating: 8.4 },
  { id: 62, title: "Inglourious Basterds", year: 2009, genre: "War", rating: 8.4 },
  { id: 63, title: "Amélie", year: 2001, genre: "Comedy", rating: 8.3 },
  { id: 64, title: "Good Will Hunting", year: 1997, genre: "Drama", rating: 8.3 },
  { id: 65, title: "Toy Story", year: 1995, genre: "Animation", rating: 8.3 },
  { id: 66, title: "2001: A Space Odyssey", year: 1968, genre: "Sci-Fi", rating: 8.3 },
  { id: 67, title: "Reservoir Dogs", year: 1992, genre: "Crime", rating: 8.3 },
  { id: 68, title: "Requiem for a Dream", year: 2000, genre: "Drama", rating: 8.3 },
  { id: 69, title: "Up", year: 2009, genre: "Animation", rating: 8.3 },
  { id: 70, title: "Citizen Kane", year: 1941, genre: "Drama", rating: 8.3 },
  { id: 71, title: "Full Metal Jacket", year: 1987, genre: "War", rating: 8.3 },
  { id: 72, title: "Scarface", year: 1983, genre: "Crime", rating: 8.3 },
  { id: 73, title: "Lawrence of Arabia", year: 1962, genre: "Adventure", rating: 8.3 },
  { id: 74, title: "Taxi Driver", year: 1976, genre: "Crime", rating: 8.2 },
  { id: 75, title: "Eternal Sunshine of the Spotless Mind", year: 2004, genre: "Romance", rating: 8.3 },
  { id: 76, title: "The Truman Show", year: 1998, genre: "Comedy", rating: 8.2 },
  { id: 77, title: "No Country for Old Men", year: 2007, genre: "Crime", rating: 8.2 },
  { id: 78, title: "The Great Dictator", year: 1940, genre: "Comedy", rating: 8.4 },
  { id: 79, title: "A Clockwork Orange", year: 1971, genre: "Sci-Fi", rating: 8.3 },
  { id: 80, title: "Snatch", year: 2000, genre: "Comedy", rating: 8.2 },
  { id: 81, title: "There Will Be Blood", year: 2007, genre: "Drama", rating: 8.2 },
  { id: 82, title: "The Big Lebowski", year: 1998, genre: "Comedy", rating: 8.1 },
  { id: 83, title: "Fargo", year: 1996, genre: "Crime", rating: 8.1 },
  { id: 84, title: "Shutter Island", year: 2010, genre: "Mystery", rating: 8.2 },
  { id: 85, title: "The Wolf of Wall Street", year: 2013, genre: "Biography", rating: 8.2 },
  { id: 86, title: "Blade Runner", year: 1982, genre: "Sci-Fi", rating: 8.1 },
  { id: 87, title: "Mad Max: Fury Road", year: 2015, genre: "Action", rating: 8.1 },
  { id: 88, title: "The Grand Budapest Hotel", year: 2014, genre: "Comedy", rating: 8.1 },
  { id: 89, title: "Pan's Labyrinth", year: 2006, genre: "Fantasy", rating: 8.2 },
  { id: 90, title: "Jurassic Park", year: 1993, genre: "Adventure", rating: 8.2 },
  { id: 91, title: "1917", year: 2019, genre: "War", rating: 8.2 },
  { id: 92, title: "Catch Me If You Can", year: 2002, genre: "Biography", rating: 8.1 },
  { id: 93, title: "Die Hard", year: 1988, genre: "Action", rating: 8.2 },
  { id: 94, title: "Gone Girl", year: 2014, genre: "Mystery", rating: 8.1 },
  { id: 95, title: "The Sixth Sense", year: 1999, genre: "Mystery", rating: 8.2 },
  { id: 96, title: "Heat", year: 1995, genre: "Action", rating: 8.3 },
  { id: 97, title: "Avengers: Doomsday", year: 2026, genre: "Action", rating: 8.5 },
  { id: 98, title: "The Mandalorian & Grogu", year: 2026, genre: "Sci-Fi", rating: 8.2 },
  { id: 99, title: "Toy Story 5", year: 2026, genre: "Animation", rating: 7.9 },
  { id: 100, title: "The Batman Part II", year: 2026, genre: "Crime", rating: 8.4 }
];

export default Movies